// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChatAPI(arg1) {
  return window['go']['main']['App']['ChatAPI'](arg1);
}

export function CreateNewGist(arg1, arg2) {
  return window['go']['main']['App']['CreateNewGist'](arg1, arg2);
}

export function CreateScreenshot(arg1) {
  return window['go']['main']['App']['CreateScreenshot'](arg1);
}

export function GetGistContent(arg1, arg2) {
  return window['go']['main']['App']['GetGistContent'](arg1, arg2);
}

export function GetGistsForAuthenticatedUser(arg1) {
  return window['go']['main']['App']['GetGistsForAuthenticatedUser'](arg1);
}

export function GetMoreInformationFromURL(arg1, arg2) {
  return window['go']['main']['App']['GetMoreInformationFromURL'](arg1, arg2);
}

export function GetMousePosition() {
  return window['go']['main']['App']['GetMousePosition']();
}

export function GetPromptList() {
  return window['go']['main']['App']['GetPromptList']();
}

export function GetPublicGists() {
  return window['go']['main']['App']['GetPublicGists']();
}

export function GetPublicRepositories() {
  return window['go']['main']['App']['GetPublicRepositories']();
}

export function GetRepositoriesForAuthenticatedUser(arg1) {
  return window['go']['main']['App']['GetRepositoriesForAuthenticatedUser'](arg1);
}

export function GetSelection(arg1) {
  return window['go']['main']['App']['GetSelection'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RegisterKeyboardShortcut(arg1) {
  return window['go']['main']['App']['RegisterKeyboardShortcut'](arg1);
}

export function SetPromptList(arg1) {
  return window['go']['main']['App']['SetPromptList'](arg1);
}

export function ShowPopWindow() {
  return window['go']['main']['App']['ShowPopWindow']();
}
