// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function AIBianxieAPI(arg1:string):Promise<main.ChatResponse>;

export function AIOpenHubAPI(arg1:string):Promise<main.ChatResponse>;

export function CanAccessGoogle():Promise<boolean>;

export function ChatAPI(arg1:string):Promise<main.ChatResponse>;

export function ChatAPIV2(arg1:string):Promise<main.ChatResponse>;

export function CreateScreenshot(arg1:context.Context):Promise<string>;

export function CreateScreenshotMac(arg1:context.Context):Promise<string>;

export function CreateScreenshotWindows(arg1:context.Context):Promise<string>;

export function GetMousePosition():Promise<any>;

export function GetPromptsCSV():Promise<string>;

export function GetSelection(arg1:context.Context):Promise<string>;

export function GetUniqueHardwareID():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function IsMac():Promise<boolean>;

export function IsUserInChina():Promise<boolean>;

export function LoadPrompts():Promise<Array<main.Prompt>>;

export function RegisterKeyboardShortcut(arg1:context.Context):Promise<void>;

export function SetShortcutList(arg1:string):Promise<void>;

export function ShowPopWindow():Promise<void>;
